In [1]:
import numpy as np
import pandas as pd
import json

In [2]:
edges = []
with open('data/state_matrix.csv', 'r') as f:
    i = 0
    for line in f:
        if i == 0:
            i += 1
        else:
            data = line.strip().split(',')
            src = data[0]
            dst = data[1]
            w = int(data[2])
            edges.append([src, dst, w])
            i += 1
edges[:5]

[['Alabama', 'Alabama', 4267],
 ['Alabama', 'Tennessee', 483],
 ['Alabama', 'New York', 437],
 ['Alabama', 'Texas', 419],
 ['Alabama', 'Georgia', 400]]

In [3]:
edges = np.array(edges)

In [4]:
states = np.unique(np.array([edge[0] for edge in edges]))

In [5]:
states

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype='<U20')

Initialize state matrix

In [6]:
n = len(states)
M = np.zeros((n, n))
M.shape

(52, 52)

Populate M with the top ten destinations for each state

In [7]:
for edge in edges:
    if edge[1]=='All other states':
        pass
    else:
        i = (states==edge[0]).argmax()
        j = (states==edge[1]).argmax()
        value = int(edge[2])
        M[i,j] = value
M[10]

array([   0.,    0.,    0.,    0.,  656.,    0.,    0.,    0.,    0.,
        853., 7658.,    0.,    0.,  664.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0., 1830.,  848.,    0.,  763.,
          0.,    0.,  869.,    0.,    0.,    0.,    0.,  748.,  877.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.])

Import population data to allocate "All other states" according to population

In [8]:
df_pop = pd.read_csv('data/nst-est2018-alldata.csv')
df_pop.head(10)

REGION DIVISION  STATE              NAME  POPESTIMATE2017
0      0        0      0     United States        325147121
1      1        0      0  Northeast Region         56072676
2      2        0      0    Midwest Region         68156035
3      3        0      0      South Region        123598424
4      4        0      0       West Region         77319986
5      3        6      1           Alabama          4875120
6      4        9      2            Alaska           739786
7      4        8      4           Arizona          7048876
8      3        7      5          Arkansas          3002997
9      4        9      6        California         39399349

In [9]:
def find_pop(state):
    "Find the population for a given state"
    return df_pop.iloc[(df_pop.NAME==state).argmax(),4]

In [10]:
total_pop = df_pop.POPESTIMATE2017[5:].sum()

In [11]:
df_state_matrix = pd.DataFrame(M, columns=states, index=states)
df_state_matrix.head()

Alabama  Alaska  Arizona  Arkansas  California  Colorado  \
Alabama      4267.0     0.0      0.0       0.0         0.0       0.0   
Alaska          0.0   105.0      0.0       0.0       199.0      70.0   
Arizona         0.0     0.0   4208.0       0.0      1198.0       0.0   
Arkansas        0.0     0.0      0.0    2802.0         0.0       0.0   
California      0.0     0.0      0.0       0.0     57893.0       0.0   

            Connecticut  Delaware  District of Columbia  Florida   ...     \
Alabama             0.0       0.0                   0.0    360.0   ...      
Alaska              0.0       0.0                   0.0      0.0   ...      
Arizona             0.0       0.0                   0.0      0.0   ...      
Arkansas            0.0       0.0                   0.0      0.0   ...      
California          0.0       0.0                   0.0      0.0   ...      

            South Dakota  Tennessee   Texas  Utah  Vermont  Virginia  \
Alabama              0.0      483.0   419.0   0.0      0.0       0.0   
Alaska               0.0        0.0   167.0   0.0      0.0       0.0   
Arizona              0.0        0.0   761.0   0.0      0.0       0.0   
Arkansas             0.0      244.0   421.0   0.0      0.0       0.0   
California           0.0        0.0  2471.0   0.0      0.0       0.0   

            Washington  West Virginia  Wisconsin  Wyoming  
Alabama            0.0            0.0        0.0      0.0  
Alaska           163.0            0.0        0.0      0.0  
Arizona            0.0            0.0        0.0      0.0  
Arkansas           0.0            0.0        0.0      0.0  
California         0.0            0.0        0.0      0.0  

[5 rows x 52 columns]

Fill zeros according to state populations

In [12]:
edges_other = np.array([edge for edge in edges if edge[1]=='All other states'])
len(edges_other)

52

In [13]:
df_called = df_pop[['NAME', 'POPESTIMATE2017']].iloc[5:].reset_index(drop=True)

In [14]:
edges_other[:5]

array([['Alabama', 'All other states', '2521'],
       ['Alaska', 'All other states', '830'],
       ['Arizona', 'All other states', '4181'],
       ['Arkansas', 'All other states', '1397'],
       ['California', 'All other states', '15580']], dtype='<U20')

In [15]:
def allocate_other(edge, M):
    """Allocate data pointing to "All other states" taking population into account"""
    state = edge[0]
    value = int(edge[2])
    temp = pd.DataFrame(df_state_matrix.loc[state][df_state_matrix.loc[state]==0])
    temp.reset_index(inplace=True)
    temp.rename(index=str, columns={'index': 'NAME'}, inplace=True)
    temp = temp.set_index('NAME').join(df_called.set_index('NAME'),
                                      lsuffix='_caller', rsuffix='_called', how='left')
    temp_total = temp.POPESTIMATE2017.sum()
    temp['w'] = temp.POPESTIMATE2017 / temp_total
    temp[state] = value * temp['w']
    i = (states==state).argmax()
    for idx, val in zip(temp.index, temp[state]):
        j = (states==idx).argmax()
        M[i,j] = int(val)
    print('Allocated values for {}'.format(state))

In [16]:
M_other = M.copy()

In [17]:
M[0]

array([4267.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
        360.,  400.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
        334.,    0.,    0.,    0.,    0.,    0.,  215.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,  437.,  261.,    0.,  235.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,  483.,  419.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.])

In [18]:
for edge in edges_other:
    allocate_other(edge, M_other)

Allocated values for Alabama
Allocated values for Alaska
Allocated values for Arizona
Allocated values for Arkansas
Allocated values for California
Allocated values for Colorado
Allocated values for Connecticut
Allocated values for Delaware
Allocated values for District of Columbia
Allocated values for Florida
Allocated values for Georgia
Allocated values for Hawaii
Allocated values for Idaho
Allocated values for Illinois
Allocated values for Indiana
Allocated values for Iowa
Allocated values for Kansas
Allocated values for Kentucky
Allocated values for Louisiana
Allocated values for Maine
Allocated values for Maryland
Allocated values for Massachusetts
Allocated values for Michigan
Allocated values for Minnesota
Allocated values for Mississippi
Allocated values for Missouri
Allocated values for Montana
Allocated values for Nebraska
Allocated values for Nevada
Allocated values for New Hampshire
Allocated values for New Jersey
Allocated values for New Mexico
Allocated values for New Yor

Distributed "All other states" by population of states outside of the top 10

In [19]:
M_other[0]

array([4267.,    8.,   85.,   36.,  477.,   68.,   43.,   11.,    8.,
        360.,  400.,   17.,   20.,  154.,   80.,   38.,   35.,   53.,
        334.,   16.,   73.,   83.,  120.,   67.,  215.,   74.,   12.,
         23.,   36.,   16.,  107.,   25.,  437.,  261.,    9.,  235.,
         47.,   50.,  155.,   40.,   12.,   60.,   10.,  483.,  419.,
         37.,    7.,  102.,   90.,   22.,   70.,    7.])

In [20]:
M_lists = []
for row in M_other:
    M_lists.append(list(row))
M_json = {'matrix': M_lists}
M_json['matrix'][0][:5]

[4267.0, 8.0, 85.0, 36.0, 477.0]

In [21]:
with open('data/state_matrix.json', 'w') as f:
    json.dump(M_json, f)

In [22]:
states_list = list(states)
states_json = {'list': states_list}

In [23]:
with open('data/states_list.json', 'w') as f:
    json.dump(states_json, f)

Write the regional matrix

In [24]:
df_pop.head(6)

REGION DIVISION  STATE              NAME  POPESTIMATE2017
0      0        0      0     United States        325147121
1      1        0      0  Northeast Region         56072676
2      2        0      0    Midwest Region         68156035
3      3        0      0      South Region        123598424
4      4        0      0       West Region         77319986
5      3        6      1           Alabama          4875120

Four regions, Northeast, Midwest, South, and West  
AAMC has Northeast, Central, South, and West

In [25]:
ne = ['Connecticut', 'Delaware', 'District of Columbia', 'Maine', 'Maryland', 
      'Massachusetts', 'New Hampshire', 'New Jersey', 'New York', 'Pennsylvania', 
      'Rhode Island', 'Vermont']
c = ['Illinois', 'Indiana', 'Iowa', 'Kansas', 'Michigan', 'Minnesota', 'Missouri',
     'Nebraska', 'North Dakota', 'Ohio', 'South Dakota', 'Wisconsin']
s = ['Alabama', 'Arkansas', 'Florida', 'Georgia', 'Kentucky', 'Louisiana', 'Mississippi',
     'North Carolina', 'Oklahoma', 'Puerto Rico', 'South Carolina', 'Tennessee', 'Texas', 
     'Virginia', 'West Virginia']
w = ['Alaska', 'Arizona', 'California', 'Colorado', 'Hawaii', 'Idaho', 'Montana', 'Nevada',
     'New Mexico', 'Oregon', 'Utah', 'Washington', 'Wyoming']

In [26]:
def aamc_region(state):
    # Allocate AAMC regions
    if state in ne:
        return 0
    elif state in c:
        return 1
    elif state in s:
        return 2
    elif state in w:
        return 3

In [27]:
df_pop['aamc_region'] = df_pop['NAME'].apply(aamc_region)

In [28]:
df_pop.head(10)

REGION DIVISION  STATE              NAME  POPESTIMATE2017  aamc_region
0      0        0      0     United States        325147121          NaN
1      1        0      0  Northeast Region         56072676          NaN
2      2        0      0    Midwest Region         68156035          NaN
3      3        0      0      South Region        123598424          NaN
4      4        0      0       West Region         77319986          NaN
5      3        6      1           Alabama          4875120          2.0
6      4        9      2            Alaska           739786          3.0
7      4        8      4           Arizona          7048876          3.0
8      3        7      5          Arkansas          3002997          2.0
9      4        9      6        California         39399349          3.0

In [49]:
df_M = pd.DataFrame(M_other, columns=states, index=states)
df_M.head()

Alabama  Alaska  Arizona  Arkansas  California  Colorado  \
Alabama      4267.0     8.0     85.0      36.0       477.0      68.0   
Alaska         21.0   105.0     31.0      13.0       199.0      70.0   
Arizona       116.0    17.0   4208.0      71.0      1198.0     134.0   
Arkansas       30.0     4.0     44.0    2802.0       248.0      35.0   
California    441.0    66.0    637.0     271.0     57893.0     508.0   

            Connecticut  Delaware  District of Columbia  Florida   ...     \
Alabama            43.0      11.0                   8.0    360.0   ...      
Alaska             15.0       4.0                   3.0     92.0   ...      
Arizona            85.0      22.0                  16.0    502.0   ...      
Arkansas           22.0       6.0                   4.0    132.0   ...      
California        323.0      86.0                  62.0   1898.0   ...      

            South Dakota  Tennessee   Texas   Utah  Vermont  Virginia  \
Alabama             10.0      483.0   419.0   37.0      7.0     102.0   
Alaska               3.0       29.0   167.0   13.0      2.0      37.0   
Arizona             20.0      160.0   761.0   74.0     14.0     202.0   
Arkansas             5.0      244.0   421.0   19.0      3.0      53.0   
California          79.0      607.0  2471.0  280.0     56.0     766.0   

            Washington  West Virginia  Wisconsin  Wyoming  
Alabama           90.0           22.0       70.0      7.0  
Alaska           163.0            8.0       25.0      2.0  
Arizona          177.0           43.0      138.0     13.0  
Arkansas          46.0           11.0       36.0      3.0  
California       671.0          164.0      524.0     52.0  

[5 rows x 52 columns]

In [54]:
temp = pd.DataFrame(df_M.reset_index()['index'].apply(aamc_region))
df_M = df_M.reset_index().join(temp, lsuffix='_caller', rsuffix='_called')\
    .set_index('index_caller').rename(index=str, columns={'index_called': 'region'})

In [60]:
df_pivot = pd.pivot_table(df_M, values=states, columns=['region'], aggfunc=np.sum)

In [65]:
temp = pd.DataFrame(df_pivot.reset_index()['index'].apply(aamc_region))
df_pivot = df_pivot.reset_index().join(temp, lsuffix='_caller', rsuffix='_called')\
    .set_index('index_caller').rename(index=str, columns={'index_called': 'region'})

In [68]:
df_pivot2 = pd.pivot_table(df_pivot, values=[0,1,2,3], index=['region'], aggfunc=np.sum)
df_pivot2

0         1         2         3
region                                        
0       176625.0   18307.0   49570.0   32232.0
1        13263.0  121016.0   34589.0   25959.0
2        15378.0   18827.0  155223.0   28987.0
3         9206.0    9742.0   22654.0  102520.0

In [76]:
region_list = df_pivot2.values.tolist()
region_json = {'matrix': region_list}

In [78]:
with open('data/region_matrix.json', 'w') as f:
    json.dump(region_json, f)

Order of region: Northeast, Central, South, West